// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_d_perp_euc
double cpp_d_perp_euc(double si_x, double si_y, double ei_x, double ei_y, double sj_x, double sj_y, double ej_x, double ej_y);
RcppExport SEXP _TRACLUS_cpp_d_perp_euc(SEXP si_xSEXP, SEXP si_ySEXP, SEXP ei_xSEXP, SEXP ei_ySEXP, SEXP sj_xSEXP, SEXP sj_ySEXP, SEXP ej_xSEXP, SEXP ej_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type si_x(si_xSEXP);
    Rcpp::traits::input_parameter< double >::type si_y(si_ySEXP);
    Rcpp::traits::input_parameter< double >::type ei_x(ei_xSEXP);
    Rcpp::traits::input_parameter< double >::type ei_y(ei_ySEXP);
    Rcpp::traits::input_parameter< double >::type sj_x(sj_xSEXP);
    Rcpp::traits::input_parameter< double >::type sj_y(sj_ySEXP);
    Rcpp::traits::input_parameter< double >::type ej_x(ej_xSEXP);
    Rcpp::traits::input_parameter< double >::type ej_y(ej_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_perp_euc(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_d_par_euc
double cpp_d_par_euc(double si_x, double si_y, double ei_x, double ei_y, double sj_x, double sj_y, double ej_x, double ej_y);
RcppExport SEXP _TRACLUS_cpp_d_par_euc(SEXP si_xSEXP, SEXP si_ySEXP, SEXP ei_xSEXP, SEXP ei_ySEXP, SEXP sj_xSEXP, SEXP sj_ySEXP, SEXP ej_xSEXP, SEXP ej_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type si_x(si_xSEXP);
    Rcpp::traits::input_parameter< double >::type si_y(si_ySEXP);
    Rcpp::traits::input_parameter< double >::type ei_x(ei_xSEXP);
    Rcpp::traits::input_parameter< double >::type ei_y(ei_ySEXP);
    Rcpp::traits::input_parameter< double >::type sj_x(sj_xSEXP);
    Rcpp::traits::input_parameter< double >::type sj_y(sj_ySEXP);
    Rcpp::traits::input_parameter< double >::type ej_x(ej_xSEXP);
    Rcpp::traits::input_parameter< double >::type ej_y(ej_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_par_euc(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_d_angle_euc
double cpp_d_angle_euc(double si_x, double si_y, double ei_x, double ei_y, double sj_x, double sj_y, double ej_x, double ej_y);
RcppExport SEXP _TRACLUS_cpp_d_angle_euc(SEXP si_xSEXP, SEXP si_ySEXP, SEXP ei_xSEXP, SEXP ei_ySEXP, SEXP sj_xSEXP, SEXP sj_ySEXP, SEXP ej_xSEXP, SEXP ej_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type si_x(si_xSEXP);
    Rcpp::traits::input_parameter< double >::type si_y(si_ySEXP);
    Rcpp::traits::input_parameter< double >::type ei_x(ei_xSEXP);
    Rcpp::traits::input_parameter< double >::type ei_y(ei_ySEXP);
    Rcpp::traits::input_parameter< double >::type sj_x(sj_xSEXP);
    Rcpp::traits::input_parameter< double >::type sj_y(sj_ySEXP);
    Rcpp::traits::input_parameter< double >::type ej_x(ej_xSEXP);
    Rcpp::traits::input_parameter< double >::type ej_y(ej_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_angle_euc(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_traclus_dist_euc
double cpp_traclus_dist_euc(double si_x, double si_y, double ei_x, double ei_y, double sj_x, double sj_y, double ej_x, double ej_y, double w_perp, double w_par, double w_angle, double eps);
RcppExport SEXP _TRACLUS_cpp_traclus_dist_euc(SEXP si_xSEXP, SEXP si_ySEXP, SEXP ei_xSEXP, SEXP ei_ySEXP, SEXP sj_xSEXP, SEXP sj_ySEXP, SEXP ej_xSEXP, SEXP ej_ySEXP, SEXP w_perpSEXP, SEXP w_parSEXP, SEXP w_angleSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type si_x(si_xSEXP);
    Rcpp::traits::input_parameter< double >::type si_y(si_ySEXP);
    Rcpp::traits::input_parameter< double >::type ei_x(ei_xSEXP);
    Rcpp::traits::input_parameter< double >::type ei_y(ei_ySEXP);
    Rcpp::traits::input_parameter< double >::type sj_x(sj_xSEXP);
    Rcpp::traits::input_parameter< double >::type sj_y(sj_ySEXP);
    Rcpp::traits::input_parameter< double >::type ej_x(ej_xSEXP);
    Rcpp::traits::input_parameter< double >::type ej_y(ej_ySEXP);
    Rcpp::traits::input_parameter< double >::type w_perp(w_perpSEXP);
    Rcpp::traits::input_parameter< double >::type w_par(w_parSEXP);
    Rcpp::traits::input_parameter< double >::type w_angle(w_angleSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_traclus_dist_euc(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y, w_perp, w_par, w_angle, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_pairwise_dists
Rcpp::NumericVector cpp_compute_pairwise_dists(Rcpp::NumericVector sx, Rcpp::NumericVector sy, Rcpp::NumericVector ex, Rcpp::NumericVector ey, double w_perp, double w_par, double w_angle, std::string method);
RcppExport SEXP _TRACLUS_cpp_compute_pairwise_dists(SEXP sxSEXP, SEXP sySEXP, SEXP exSEXP, SEXP eySEXP, SEXP w_perpSEXP, SEXP w_parSEXP, SEXP w_angleSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sy(sySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< double >::type w_perp(w_perpSEXP);
    Rcpp::traits::input_parameter< double >::type w_par(w_parSEXP);
    Rcpp::traits::input_parameter< double >::type w_angle(w_angleSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_pairwise_dists(sx, sy, ex, ey, w_perp, w_par, w_angle, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_count_neighbours_multi_eps
Rcpp::List cpp_count_neighbours_multi_eps(Rcpp::NumericVector pair_dists, int n_sample, Rcpp::NumericVector eps_grid);
RcppExport SEXP _TRACLUS_cpp_count_neighbours_multi_eps(SEXP pair_distsSEXP, SEXP n_sampleSEXP, SEXP eps_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pair_dists(pair_distsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample(n_sampleSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eps_grid(eps_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_count_neighbours_multi_eps(pair_dists, n_sample, eps_grid));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_neighbourhoods
Rcpp::List cpp_compute_neighbourhoods(Rcpp::NumericVector sx, Rcpp::NumericVector sy, Rcpp::NumericVector ex, Rcpp::NumericVector ey, double eps, double w_perp, double w_par, double w_angle, std::string method, bool show_progress);
RcppExport SEXP _TRACLUS_cpp_compute_neighbourhoods(SEXP sxSEXP, SEXP sySEXP, SEXP exSEXP, SEXP eySEXP, SEXP epsSEXP, SEXP w_perpSEXP, SEXP w_parSEXP, SEXP w_angleSEXP, SEXP methodSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sy(sySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type w_perp(w_perpSEXP);
    Rcpp::traits::input_parameter< double >::type w_par(w_parSEXP);
    Rcpp::traits::input_parameter< double >::type w_angle(w_angleSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_neighbourhoods(sx, sy, ex, ey, eps, w_perp, w_par, w_angle, method, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partition_all
Rcpp::List cpp_partition_all(Rcpp::CharacterVector traj_ids, Rcpp::NumericVector x_coords, Rcpp::NumericVector y_coords, int method);
RcppExport SEXP _TRACLUS_cpp_partition_all(SEXP traj_idsSEXP, SEXP x_coordsSEXP, SEXP y_coordsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type traj_ids(traj_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_coords(x_coordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_coords(y_coordsSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partition_all(traj_ids, x_coords, y_coords, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partition_single
Rcpp::IntegerVector cpp_partition_single(Rcpp::NumericVector x_coords, Rcpp::NumericVector y_coords, int method);
RcppExport SEXP _TRACLUS_cpp_partition_single(SEXP x_coordsSEXP, SEXP y_coordsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_coords(x_coordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_coords(y_coordsSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partition_single(x_coords, y_coords, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mdl_costpar
double cpp_mdl_costpar(double part_sx, double part_sy, double part_ex, double part_ey, Rcpp::NumericVector sub_x, Rcpp::NumericVector sub_y, int method);
RcppExport SEXP _TRACLUS_cpp_mdl_costpar(SEXP part_sxSEXP, SEXP part_sySEXP, SEXP part_exSEXP, SEXP part_eySEXP, SEXP sub_xSEXP, SEXP sub_ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type part_sx(part_sxSEXP);
    Rcpp::traits::input_parameter< double >::type part_sy(part_sySEXP);
    Rcpp::traits::input_parameter< double >::type part_ex(part_exSEXP);
    Rcpp::traits::input_parameter< double >::type part_ey(part_eySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sub_x(sub_xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sub_y(sub_ySEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mdl_costpar(part_sx, part_sy, part_ex, part_ey, sub_x, sub_y, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mdl_costnopar
double cpp_mdl_costnopar(Rcpp::NumericVector sub_x, Rcpp::NumericVector sub_y, int method);
RcppExport SEXP _TRACLUS_cpp_mdl_costnopar(SEXP sub_xSEXP, SEXP sub_ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sub_x(sub_xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sub_y(sub_ySEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mdl_costnopar(sub_x, sub_y, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_haversine_dist
double cpp_haversine_dist(double lon1, double lat1, double lon2, double lat2);
RcppExport SEXP _TRACLUS_cpp_haversine_dist(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_haversine_dist(lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_initial_bearing
double cpp_initial_bearing(double lon1, double lat1, double lon2, double lat2);
RcppExport SEXP _TRACLUS_cpp_initial_bearing(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_initial_bearing(lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cross_track_dist
double cpp_cross_track_dist(double plon, double plat, double lon1, double lat1, double lon2, double lat2);
RcppExport SEXP _TRACLUS_cpp_cross_track_dist(SEXP plonSEXP, SEXP platSEXP, SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type plon(plonSEXP);
    Rcpp::traits::input_parameter< double >::type plat(platSEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cross_track_dist(plon, plat, lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_along_track_signed
double cpp_along_track_signed(double plon, double plat, double lon1, double lat1, double lon2, double lat2);
RcppExport SEXP _TRACLUS_cpp_along_track_signed(SEXP plonSEXP, SEXP platSEXP, SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type plon(plonSEXP);
    Rcpp::traits::input_parameter< double >::type plat(platSEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_along_track_signed(plon, plat, lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_d_perp_sph
double cpp_d_perp_sph(double lon_si, double lat_si, double lon_ei, double lat_ei, double lon_sj, double lat_sj, double lon_ej, double lat_ej);
RcppExport SEXP _TRACLUS_cpp_d_perp_sph(SEXP lon_siSEXP, SEXP lat_siSEXP, SEXP lon_eiSEXP, SEXP lat_eiSEXP, SEXP lon_sjSEXP, SEXP lat_sjSEXP, SEXP lon_ejSEXP, SEXP lat_ejSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_si(lon_siSEXP);
    Rcpp::traits::input_parameter< double >::type lat_si(lat_siSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ei(lon_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ei(lat_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lon_sj(lon_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lat_sj(lat_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ej(lon_ejSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ej(lat_ejSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_perp_sph(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej));
    return rcpp_result_gen;
END_RCPP
}
// cpp_d_par_sph
double cpp_d_par_sph(double lon_si, double lat_si, double lon_ei, double lat_ei, double lon_sj, double lat_sj, double lon_ej, double lat_ej);
RcppExport SEXP _TRACLUS_cpp_d_par_sph(SEXP lon_siSEXP, SEXP lat_siSEXP, SEXP lon_eiSEXP, SEXP lat_eiSEXP, SEXP lon_sjSEXP, SEXP lat_sjSEXP, SEXP lon_ejSEXP, SEXP lat_ejSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_si(lon_siSEXP);
    Rcpp::traits::input_parameter< double >::type lat_si(lat_siSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ei(lon_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ei(lat_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lon_sj(lon_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lat_sj(lat_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ej(lon_ejSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ej(lat_ejSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_par_sph(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej));
    return rcpp_result_gen;
END_RCPP
}
// cpp_d_angle_sph
double cpp_d_angle_sph(double lon_si, double lat_si, double lon_ei, double lat_ei, double lon_sj, double lat_sj, double lon_ej, double lat_ej);
RcppExport SEXP _TRACLUS_cpp_d_angle_sph(SEXP lon_siSEXP, SEXP lat_siSEXP, SEXP lon_eiSEXP, SEXP lat_eiSEXP, SEXP lon_sjSEXP, SEXP lat_sjSEXP, SEXP lon_ejSEXP, SEXP lat_ejSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_si(lon_siSEXP);
    Rcpp::traits::input_parameter< double >::type lat_si(lat_siSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ei(lon_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ei(lat_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lon_sj(lon_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lat_sj(lat_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ej(lon_ejSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ej(lat_ejSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_d_angle_sph(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej));
    return rcpp_result_gen;
END_RCPP
}
// cpp_traclus_dist_sph
double cpp_traclus_dist_sph(double lon_si, double lat_si, double lon_ei, double lat_ei, double lon_sj, double lat_sj, double lon_ej, double lat_ej, double w_perp, double w_par, double w_angle, double eps);
RcppExport SEXP _TRACLUS_cpp_traclus_dist_sph(SEXP lon_siSEXP, SEXP lat_siSEXP, SEXP lon_eiSEXP, SEXP lat_eiSEXP, SEXP lon_sjSEXP, SEXP lat_sjSEXP, SEXP lon_ejSEXP, SEXP lat_ejSEXP, SEXP w_perpSEXP, SEXP w_parSEXP, SEXP w_angleSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_si(lon_siSEXP);
    Rcpp::traits::input_parameter< double >::type lat_si(lat_siSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ei(lon_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ei(lat_eiSEXP);
    Rcpp::traits::input_parameter< double >::type lon_sj(lon_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lat_sj(lat_sjSEXP);
    Rcpp::traits::input_parameter< double >::type lon_ej(lon_ejSEXP);
    Rcpp::traits::input_parameter< double >::type lat_ej(lat_ejSEXP);
    Rcpp::traits::input_parameter< double >::type w_perp(w_perpSEXP);
    Rcpp::traits::input_parameter< double >::type w_par(w_parSEXP);
    Rcpp::traits::input_parameter< double >::type w_angle(w_angleSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_traclus_dist_sph(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej, w_perp, w_par, w_angle, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRACLUS_cpp_d_perp_euc", (DL_FUNC) &_TRACLUS_cpp_d_perp_euc, 8},
    {"_TRACLUS_cpp_d_par_euc", (DL_FUNC) &_TRACLUS_cpp_d_par_euc, 8},
    {"_TRACLUS_cpp_d_angle_euc", (DL_FUNC) &_TRACLUS_cpp_d_angle_euc, 8},
    {"_TRACLUS_cpp_traclus_dist_euc", (DL_FUNC) &_TRACLUS_cpp_traclus_dist_euc, 12},
    {"_TRACLUS_cpp_compute_pairwise_dists", (DL_FUNC) &_TRACLUS_cpp_compute_pairwise_dists, 8},
    {"_TRACLUS_cpp_count_neighbours_multi_eps", (DL_FUNC) &_TRACLUS_cpp_count_neighbours_multi_eps, 3},
    {"_TRACLUS_cpp_compute_neighbourhoods", (DL_FUNC) &_TRACLUS_cpp_compute_neighbourhoods, 10},
    {"_TRACLUS_cpp_partition_all", (DL_FUNC) &_TRACLUS_cpp_partition_all, 4},
    {"_TRACLUS_cpp_partition_single", (DL_FUNC) &_TRACLUS_cpp_partition_single, 3},
    {"_TRACLUS_cpp_mdl_costpar", (DL_FUNC) &_TRACLUS_cpp_mdl_costpar, 7},
    {"_TRACLUS_cpp_mdl_costnopar", (DL_FUNC) &_TRACLUS_cpp_mdl_costnopar, 3},
    {"_TRACLUS_cpp_haversine_dist", (DL_FUNC) &_TRACLUS_cpp_haversine_dist, 4},
    {"_TRACLUS_cpp_initial_bearing", (DL_FUNC) &_TRACLUS_cpp_initial_bearing, 4},
    {"_TRACLUS_cpp_cross_track_dist", (DL_FUNC) &_TRACLUS_cpp_cross_track_dist, 6},
    {"_TRACLUS_cpp_along_track_signed", (DL_FUNC) &_TRACLUS_cpp_along_track_signed, 6},
    {"_TRACLUS_cpp_d_perp_sph", (DL_FUNC) &_TRACLUS_cpp_d_perp_sph, 8},
    {"_TRACLUS_cpp_d_par_sph", (DL_FUNC) &_TRACLUS_cpp_d_par_sph, 8},
    {"_TRACLUS_cpp_d_angle_sph", (DL_FUNC) &_TRACLUS_cpp_d_angle_sph, 8},
    {"_TRACLUS_cpp_traclus_dist_sph", (DL_FUNC) &_TRACLUS_cpp_traclus_dist_sph, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRACLUS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
