# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute euclidean perpendicular distance between two segments (C++)
#' @param si_x,si_y,ei_x,ei_y Coordinates of segment i
#' @param sj_x,sj_y,ej_x,ej_y Coordinates of segment j
#' @return Perpendicular distance (double)
#' @keywords internal
.cpp_d_perp_euc <- function(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y) {
    .Call(`_TRACLUS_cpp_d_perp_euc`, si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y)
}

#' Compute euclidean parallel distance between two segments (C++)
#' @param si_x,si_y,ei_x,ei_y Coordinates of segment i
#' @param sj_x,sj_y,ej_x,ej_y Coordinates of segment j
#' @return Parallel distance (double)
#' @keywords internal
.cpp_d_par_euc <- function(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y) {
    .Call(`_TRACLUS_cpp_d_par_euc`, si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y)
}

#' Compute euclidean angle distance between two segments (C++)
#' @param si_x,si_y,ei_x,ei_y Coordinates of segment i
#' @param sj_x,sj_y,ej_x,ej_y Coordinates of segment j
#' @return Angle distance (double)
#' @keywords internal
.cpp_d_angle_euc <- function(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y) {
    .Call(`_TRACLUS_cpp_d_angle_euc`, si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y)
}

#' Compute weighted total euclidean distance between two segments (C++)
#' @param si_x,si_y,ei_x,ei_y Coordinates of segment i
#' @param sj_x,sj_y,ej_x,ej_y Coordinates of segment j
#' @param w_perp,w_par,w_angle Distance component weights
#' @param eps Epsilon threshold for early termination
#' @return Weighted total distance (double)
#' @keywords internal
.cpp_traclus_dist_euc <- function(si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y, w_perp, w_par, w_angle, eps) {
    .Call(`_TRACLUS_cpp_traclus_dist_euc`, si_x, si_y, ei_x, ei_y, sj_x, sj_y, ej_x, ej_y, w_perp, w_par, w_angle, eps)
}

#' Compute all pairwise TRACLUS distances for a sample of segments (C++)
#'
#' Computes the full triangular distance matrix for `n` segments in a single
#' C++ call, replacing the R loop of n*(n-1)/2 individual C++ dispatches used
#' in Phase 1 of [tc_estimate_params()].
#'
#' The result is stored in row-major triangular order: the k-th element
#' corresponds to pair (i, j) with i < j (0-indexed) where
#' k = i*(n-1) - i*(i-1)/2 + (j-i-1).
#'
#' @param sx,sy,ex,ey NumericVectors of segment start/end coordinates.
#' @param w_perp,w_par,w_angle Distance weights.
#' @param method `"euclidean"` or `"haversine"`.
#' @return NumericVector of length n*(n-1)/2 with pairwise distances.
#' @keywords internal
.cpp_compute_pairwise_dists <- function(sx, sy, ex, ey, w_perp, w_par, w_angle, method) {
    .Call(`_TRACLUS_cpp_compute_pairwise_dists`, sx, sy, ex, ey, w_perp, w_par, w_angle, method)
}

#' Count neighbourhood sizes for multiple eps candidates (C++)
#'
#' Replaces Phase 2 of [tc_estimate_params()]: given a pre-computed triangular
#' distance matrix and a sorted grid of eps candidates, counts neighbourhood
#' sizes for every segment and every eps in a single O(n_pairs * log(n_eps)) pass.
#'
#' For each pair (i,j) with distance d, binary search finds all eps candidates
#' >= d; the counts for segment i and j are incremented for those eps values.
#' Self-inclusion (+1) is added at the end.
#'
#' @param pair_dists NumericVector of length n*(n-1)/2 (triangular, row-major,
#'   i < j ordering produced by `.cpp_compute_pairwise_dists()`).
#' @param n_sample Integer; number of sampled segments.
#' @param eps_grid NumericVector of eps candidates, sorted ascending.
#' @return List with:
#'   \item{mean_nb_sizes}{mean neighbourhood size per eps (length n_eps)}
#'   \item{entropy_vals}{distribution entropy per eps (length n_eps)}
#' @keywords internal
.cpp_count_neighbours_multi_eps <- function(pair_dists, n_sample, eps_grid) {
    .Call(`_TRACLUS_cpp_count_neighbours_multi_eps`, pair_dists, n_sample, eps_grid)
}

#' Compute epsilon-neighbourhoods for all segments (C++)
#'
#' Computes pairwise distances between all line segments using the TRACLUS
#' weighted distance function. Uses a triangular loop (i < j) to exploit
#' symmetry and early termination when accumulated distance exceeds eps.
#' Returns adjacency lists of segment indices within eps distance.
#'
#' @param sx NumericVector of segment start x-coordinates
#' @param sy NumericVector of segment start y-coordinates
#' @param ex NumericVector of segment end x-coordinates
#' @param ey NumericVector of segment end y-coordinates
#' @param eps Distance threshold
#' @param w_perp Weight for perpendicular distance
#' @param w_par Weight for parallel distance
#' @param w_angle Weight for angle distance
#' @param method Distance method: "euclidean" or "haversine"
#' @param show_progress Whether to show progress bar (only for n > 5000)
#' @return List of integer vectors (adjacency lists, 1-indexed for R).
#'   Each element contains the indices of neighbouring segments within eps.
#' @keywords internal
.cpp_compute_neighbourhoods <- function(sx, sy, ex, ey, eps, w_perp, w_par, w_angle, method, show_progress) {
    .Call(`_TRACLUS_cpp_compute_neighbourhoods`, sx, sy, ex, ey, eps, w_perp, w_par, w_angle, method, show_progress)
}

#' Partition all trajectories using MDL-based approximate partitioning
#'
#' Implements the approximate trajectory partitioning algorithm from
#' Paper Figure 8. Each trajectory is partitioned independently based on
#' the MDL principle. Returns a data.frame of line segments connecting
#' consecutive characteristic points.
#'
#' @param traj_ids Character vector of trajectory IDs (one per point).
#' @param x_coords Numeric vector of x-coordinates (or longitudes).
#' @param y_coords Numeric vector of y-coordinates (or latitudes).
#' @param method Integer: 0 for euclidean, 1 for haversine.
#' @return A List with elements: traj_id, seg_id, sx, sy, ex, ey.
#' @keywords internal
.cpp_partition_all <- function(traj_ids, x_coords, y_coords, method) {
    .Call(`_TRACLUS_cpp_partition_all`, traj_ids, x_coords, y_coords, method)
}

#' Partition a single trajectory (for testing)
#'
#' Returns a vector of characteristic point indices (1-based, for R).
#'
#' @param x_coords Numeric vector of x-coordinates.
#' @param y_coords Numeric vector of y-coordinates.
#' @param method Integer: 0 for euclidean, 1 for haversine.
#' @return Integer vector of characteristic point indices (1-based).
#' @keywords internal
.cpp_partition_single <- function(x_coords, y_coords, method) {
    .Call(`_TRACLUS_cpp_partition_single`, x_coords, y_coords, method)
}

#' Compute MDL cost of partitioning (costpar) for testing
#'
#' @param part_sx,part_sy,part_ex,part_ey Partition segment coordinates.
#' @param sub_x Numeric vector of sub-segment x-coordinates (all points).
#' @param sub_y Numeric vector of sub-segment y-coordinates (all points).
#' @param method Integer: 0 for euclidean, 1 for haversine.
#' @return The MDL costpar value (double).
#' @keywords internal
.cpp_mdl_costpar <- function(part_sx, part_sy, part_ex, part_ey, sub_x, sub_y, method) {
    .Call(`_TRACLUS_cpp_mdl_costpar`, part_sx, part_sy, part_ex, part_ey, sub_x, sub_y, method)
}

#' Compute MDL cost of no-partitioning (costnopar) for testing
#'
#' @param sub_x Numeric vector of point x-coordinates.
#' @param sub_y Numeric vector of point y-coordinates.
#' @param method Integer: 0 for euclidean, 1 for haversine.
#' @return The MDL costnopar value (double).
#' @keywords internal
.cpp_mdl_costnopar <- function(sub_x, sub_y, method) {
    .Call(`_TRACLUS_cpp_mdl_costnopar`, sub_x, sub_y, method)
}

#' Compute haversine distance between two points (C++)
#' @param lon1,lat1 Coordinates of point 1 in degrees
#' @param lon2,lat2 Coordinates of point 2 in degrees
#' @return Distance in meters (double)
#' @keywords internal
.cpp_haversine_dist <- function(lon1, lat1, lon2, lat2) {
    .Call(`_TRACLUS_cpp_haversine_dist`, lon1, lat1, lon2, lat2)
}

#' Compute initial bearing between two points (C++)
#' @param lon1,lat1 Coordinates of point 1 in degrees
#' @param lon2,lat2 Coordinates of point 2 in degrees
#' @return Bearing in degrees [0, 360) (double)
#' @keywords internal
.cpp_initial_bearing <- function(lon1, lat1, lon2, lat2) {
    .Call(`_TRACLUS_cpp_initial_bearing`, lon1, lat1, lon2, lat2)
}

#' Compute cross-track distance from point to great circle (C++)
#' @param plon,plat Point coordinates in degrees
#' @param lon1,lat1,lon2,lat2 Great circle endpoints in degrees
#' @return Absolute cross-track distance in meters (double)
#' @keywords internal
.cpp_cross_track_dist <- function(plon, plat, lon1, lat1, lon2, lat2) {
    .Call(`_TRACLUS_cpp_cross_track_dist`, plon, plat, lon1, lat1, lon2, lat2)
}

#' Compute signed along-track distance (C++)
#' @param plon,plat Point coordinates in degrees
#' @param lon1,lat1,lon2,lat2 Great circle endpoints in degrees
#' @return Signed along-track distance in meters (double)
#' @keywords internal
.cpp_along_track_signed <- function(plon, plat, lon1, lat1, lon2, lat2) {
    .Call(`_TRACLUS_cpp_along_track_signed`, plon, plat, lon1, lat1, lon2, lat2)
}

#' Compute spherical perpendicular distance between two segments (C++)
#' @param lon_si,lat_si,lon_ei,lat_ei Segment i endpoints in degrees
#' @param lon_sj,lat_sj,lon_ej,lat_ej Segment j endpoints in degrees
#' @return Perpendicular distance in meters (double)
#' @keywords internal
.cpp_d_perp_sph <- function(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej) {
    .Call(`_TRACLUS_cpp_d_perp_sph`, lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej)
}

#' Compute spherical parallel distance between two segments (C++)
#' @param lon_si,lat_si,lon_ei,lat_ei Segment i endpoints in degrees
#' @param lon_sj,lat_sj,lon_ej,lat_ej Segment j endpoints in degrees
#' @return Parallel distance in meters (double)
#' @keywords internal
.cpp_d_par_sph <- function(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej) {
    .Call(`_TRACLUS_cpp_d_par_sph`, lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej)
}

#' Compute spherical angle distance between two segments (C++)
#' @param lon_si,lat_si,lon_ei,lat_ei Segment i endpoints in degrees
#' @param lon_sj,lat_sj,lon_ej,lat_ej Segment j endpoints in degrees
#' @return Angle distance in meters (double)
#' @keywords internal
.cpp_d_angle_sph <- function(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej) {
    .Call(`_TRACLUS_cpp_d_angle_sph`, lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej)
}

#' Compute weighted total spherical distance between two segments (C++)
#' @param lon_si,lat_si,lon_ei,lat_ei Segment i endpoints in degrees
#' @param lon_sj,lat_sj,lon_ej,lat_ej Segment j endpoints in degrees
#' @param w_perp,w_par,w_angle Distance component weights
#' @param eps Epsilon threshold for early termination
#' @return Weighted total distance in meters (double)
#' @keywords internal
.cpp_traclus_dist_sph <- function(lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej, w_perp, w_par, w_angle, eps) {
    .Call(`_TRACLUS_cpp_traclus_dist_sph`, lon_si, lat_si, lon_ei, lat_ei, lon_sj, lat_sj, lon_ej, lat_ej, w_perp, w_par, w_angle, eps)
}

